version: "3.4"

services:
  app:
    build: .
    image: geodjango
    environment:
      PYTHONDONTWRITEBYTECODE: "no-write"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: gis
      DB_USER: geodjango
      DB_PASSWORD: passw0rd
      SECRET_KEY: e&JiovbN*CFuD3ruNzFjGJit43C^Gky3
      DEBUG: True
      DEVELOPMENT_MODE: True
      ALLOWED_IPV4: 192.168.1.3
      ALLOWED_DOMAIN: zgt.grgic.cloud
      LANGUAGE_CODE: hr
      TIME_ZONE: Europe/Zagreb
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: changeme
      DJANGO_SUPERUSER_EMAIL: admin@admin.org
    ports:
      - 9001:8000
    volumes:
      - .:/code
    depends_on:
      - db
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py createsuperuser --noinput
      && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgis/postgis:14-3.1-alpine
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: geodjango
      POSTGRES_PASSWORD: passw0rd
    expose:
      - 5432
