# Generated by Django 4.1.6 on 2023-02-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='StaticFeed',
        ),
        migrations.RenameField(
            model_name='staticfeed',
            old_name='name',
            new_name='provider',
        ),
    ]
