# Generated by Django 4.1.6 on 2023-02-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_utils', '0002_rename_provider_staticfeed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticfeed',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
