# Generated by Django 4.1.7 on 2023-04-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_trip_checked_integrity_at'),
        ('admin_utils', '0003_alter_staticfeed_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticfeed',
            name='agency',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_feed', to='search.agency'),
        ),
    ]
