# Generated by Django 4.1.6 on 2023-02-19 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=100)),
                ('agency_url', models.URLField()),
                ('agency_phone', models.CharField(max_length=20)),
                ('agency_email', models.EmailField(max_length=20)),
                ('agency_fare_url', models.EmailField(max_length=200)),
                ('provider', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=20)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('provider', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('exception_type', models.IntegerField()),
                ('provider', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('route_long_name', models.CharField(max_length=200)),
                ('route_type', models.IntegerField()),
                ('route_color', models.CharField(blank=True, max_length=6, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=6, null=True)),
                ('provider', models.CharField(max_length=10)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='search.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=200)),
                ('stop_code', models.CharField(blank=True, max_length=10, null=True)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('location_type', models.IntegerField(blank=True, null=True)),
                ('provider', models.CharField(max_length=10)),
                ('parent_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='search.stop')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(max_length=200)),
                ('trip_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('service_id', models.CharField(max_length=20)),
                ('block_id', models.IntegerField(blank=True, null=True)),
                ('bikes_allowed', models.IntegerField(blank=True, null=True)),
                ('wheelchair_accessible', models.IntegerField(blank=True, null=True)),
                ('provider', models.CharField(max_length=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='search.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DurationField()),
                ('departure_time', models.DurationField()),
                ('stop_sequence', models.IntegerField()),
                ('delay_arrival', models.DurationField(default=datetime.timedelta)),
                ('delay_departure', models.DurationField(default=datetime.timedelta)),
                ('updated_at', models.DateTimeField(null=True)),
                ('provider', models.CharField(max_length=10)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='search.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='search.trip')),
            ],
        ),
    ]
