# Generated by Django 4.1.6 on 2023-02-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_stop_sq',
            field=models.IntegerField(default=0),
        ),
    ]
