# Generated by Django 4.1.6 on 2023-02-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_trip_current_stop_sq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_stop_sq',
            field=models.IntegerField(default=1),
        ),
    ]
