# Generated by Django 4.1.6 on 2023-02-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_trip_current_stop_sq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='current_stop_sq',
        ),
    ]
